version: '3.9'
services:

  postgres-data:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=warehouse
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    networks:
      - data-net

  chrome:
    image: selenium/node-chrome:3.141.59-20210607
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    networks:
      - data-net

  selenium-hub:
    image: selenium/hub:3.141.59-20210607
    container_name: selenium-hub
    ports:
      - "4444:4444"
    networks:
      - data-net

  app:
    build:
        context: ./webapp
    container_name: app
    depends_on:
      - selenium-hub
    ports:
      - "5000:5000"
    volumes:
      - ./webapp:/var/www
    networks:
      - data-net

networks:
  data-net:
    driver: bridge

